name: AzureARMDeploy
on: 
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

        
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
